#!/usr/bin/env bash
# Guard against hand-edits to CHANGELOG.md (§8.4 of OSS_SPEC.md).
#
# CHANGELOG.md is regenerated by scripts/generate-changelog.sh during
# the release workflow. Manual edits are forbidden because they desync
# the file from the conventional-commit history that the release
# workflow rebuilds from.
#
# This hook is allowed to pass when the commit is itself a release
# commit (the message starts with `chore(release):`) or when the
# environment variable ZTF_RELEASE=1 is set, which the release
# workflow exports while running generate-changelog.sh.
set -euo pipefail

if [ "${ZTF_RELEASE:-0}" = "1" ]; then
  exit 0
fi

# Inspect the in-progress commit message if pre-commit gave us one.
if [ -n "${PRE_COMMIT_COMMIT_MSG_SOURCE:-}" ] && [ -n "${PRE_COMMIT_COMMIT_MSG:-}" ]; then
  if [ -f "$PRE_COMMIT_COMMIT_MSG" ]; then
    first_line="$(head -n1 "$PRE_COMMIT_COMMIT_MSG")"
    case "$first_line" in
      chore\(release\):*) exit 0 ;;
    esac
  fi
fi

cat >&2 <<'MSG'
CHANGELOG.md is generated by scripts/generate-changelog.sh during the
release workflow and must not be edited by hand. If you really need
to edit it (e.g. backfilling history before the first release), set
ZTF_RELEASE=1 in the environment for this commit:

    ZTF_RELEASE=1 git commit ...

Otherwise, drop the CHANGELOG.md change and re-stage your other files.
MSG
exit 1
